-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS public.sms_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone TEXT NOT NULL,
  country_code TEXT NOT NULL DEFAULT '+86',
  code TEXT NOT NULL,
  expires_at TIMESTAMP NOT NULL DEFAULT (NOW() + INTERVAL '10 minutes'),
  used BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sms_codes_phone ON public.sms_codes(phone);
CREATE INDEX IF NOT EXISTS idx_sms_codes_expires ON public.sms_codes(expires_at);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS invite_code TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS device_id TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMP;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_guest BOOLEAN DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_invite_code ON public.profiles(invite_code) WHERE invite_code IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  plan_id TEXT NOT NULL CHECK (plan_id IN ('personal', 'family')),
  status TEXT DEFAULT 'inactive' CHECK (status IN ('active', 'expiring', 'inactive', 'cancelled')),
  started_at TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP NOT NULL,
  auto_renew BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON public.subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON public.subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_expires ON public.subscriptions(expires_at);

CREATE TABLE IF NOT EXISTS public.subscription_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  plan_id TEXT NOT NULL CHECK (plan_id IN ('personal', 'family')),
  original_price DECIMAL(10, 2) NOT NULL,
  discount_amount DECIMAL(10, 2) DEFAULT 0,
  final_price DECIMAL(10, 2) NOT NULL,
  has_invite_discount BOOLEAN DEFAULT false,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'cancelled', 'expired')),
  payment_method TEXT,
  external_order_id TEXT,
  expires_at TIMESTAMP NOT NULL DEFAULT (NOW() + INTERVAL '30 minutes'),
  created_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_user ON public.subscription_orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.subscription_orders(status);

CREATE TABLE IF NOT EXISTS public.announcements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  type TEXT DEFAULT 'info' CHECK (type IN ('info', 'warning', 'critical', 'update')),
  is_active BOOLEAN DEFAULT true,
  start_at TIMESTAMP DEFAULT NOW(),
  end_at TIMESTAMP,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_announcements_active ON public.announcements(is_active);
CREATE INDEX IF NOT EXISTS idx_announcements_dates ON public.announcements(start_at, end_at);

ALTER TABLE public.sms_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscription_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "用户可查看自己的验证码" ON public.sms_codes;
CREATE POLICY "用户可查看自己的验证码" ON public.sms_codes FOR SELECT USING (phone = auth.jwt()->>'phone');

DROP POLICY IF EXISTS "系统可创建验证码" ON public.sms_codes;
CREATE POLICY "系统可创建验证码" ON public.sms_codes FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "用户可查看自己的订阅" ON public.subscriptions;
CREATE POLICY "用户可查看自己的订阅" ON public.subscriptions FOR SELECT USING (user_id = auth.uid());

DROP POLICY IF EXISTS "系统可创建订阅" ON public.subscriptions;
CREATE POLICY "系统可创建订阅" ON public.subscriptions FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "系统可更新订阅" ON public.subscriptions;
CREATE POLICY "系统可更新订阅" ON public.subscriptions FOR UPDATE USING (user_id = auth.uid());

DROP POLICY IF EXISTS "用户可查看自己的订单" ON public.subscription_orders;
CREATE POLICY "用户可查看自己的订单" ON public.subscription_orders FOR SELECT USING (user_id = auth.uid());

DROP POLICY IF EXISTS "系统可创建订单" ON public.subscription_orders;
CREATE POLICY "系统可创建订单" ON public.subscription_orders FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "系统可更新订单" ON public.subscription_orders;
CREATE POLICY "系统可更新订单" ON public.subscription_orders FOR UPDATE USING (user_id = auth.uid());

DROP POLICY IF EXISTS "所有人可查看公告" ON public.announcements;
CREATE POLICY "所有人可查看公告" ON public.announcements FOR SELECT USING (is_active = true AND (end_at IS NULL OR end_at > NOW()));

DROP POLICY IF EXISTS "管理员可管理公告" ON public.announcements;
CREATE POLICY "管理员可管理公告" ON public.announcements FOR ALL USING (auth.uid() IS NOT NULL);