-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 用户资料表
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  phone TEXT UNIQUE,
  email TEXT,
  nickname TEXT,
  avatar_url TEXT,
  gender TEXT CHECK (gender IN ('male', 'female', 'secret')),
  birth_date DATE,
  city TEXT,
  country TEXT,
  language TEXT DEFAULT 'zh',
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  emergency_contact_relation TEXT,
  blood_type TEXT CHECK (blood_type IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'unknown')),
  allergies TEXT,
  medical_history TEXT,
  current_medication TEXT,
  medical_notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- SOS记录表
CREATE TABLE public.sos_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  trigger_method TEXT NOT NULL CHECK (trigger_method IN ('manual', 'auto', 'voice')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'timeout', 'rescued', 'cancelled')),
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  address TEXT,
  city TEXT,
  country TEXT,
  alert_type TEXT,
  stage INTEGER DEFAULT 1 CHECK (stage IN (1, 2, 3, 4, 5)),
  stage_started_at TIMESTAMP DEFAULT NOW(),
  confirmed_at TIMESTAMP,
  confirmed_by TEXT CHECK (confirmed_by IN ('flashlight', 'email', 'admin', 'auto')),
  rescue_triggered_at TIMESTAMP,
  rescue_triggered_by UUID REFERENCES public.profiles(id),
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 救援待处理队列
CREATE TABLE public.rescue_pending (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sos_id UUID NOT NULL REFERENCES public.sos_records(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'urgent', 'completed', 'timeout')),
  priority INTEGER DEFAULT 1,
  user_phone TEXT,
  user_email TEXT,
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  address TEXT,
  nearest_shelter_id UUID,
  nearest_shelter_name TEXT,
  nearest_shelter_distance DECIMAL(10, 2),
  rescue_org_name TEXT,
  rescue_org_phone TEXT,
  rescue_org_email TEXT,
  alert_context JSONB,
  admin_notified_at TIMESTAMP,
  admin_processed_at TIMESTAMP,
  admin_processed_by UUID REFERENCES public.profiles(id),
  admin_notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 1公里互助订阅表
CREATE TABLE public.mutual_aid_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  is_active BOOLEAN DEFAULT true,
  subscribed_at TIMESTAMP DEFAULT NOW(),
  unsubscribed_at TIMESTAMP,
  last_reward_at TIMESTAMP,
  total_rewards INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id)
);

-- 互助救援参与记录
CREATE TABLE public.mutual_aid_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sos_id UUID NOT NULL REFERENCES public.sos_records(id) ON DELETE CASCADE,
  responder_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'responding' CHECK (status IN ('responding', 'arrived', 'verified', 'cancelled')),
  responded_at TIMESTAMP DEFAULT NOW(),
  arrived_at TIMESTAMP,
  verified_at TIMESTAMP,
  reward_amount DECIMAL(10, 2) DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 家庭组表
CREATE TABLE public.family_groups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  invite_code TEXT UNIQUE NOT NULL,
  admin_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  max_members INTEGER DEFAULT 6,
  location_sharing_enabled BOOLEAN DEFAULT true,
  sos_sync_enabled BOOLEAN DEFAULT true,
  alert_sync_enabled BOOLEAN DEFAULT true,
  evacuation_meeting_point TEXT,
  evacuation_meeting_lat DECIMAL(10, 8),
  evacuation_meeting_lng DECIMAL(11, 8),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 家庭成员表
CREATE TABLE public.family_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID NOT NULL REFERENCES public.family_groups(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
  joined_at TIMESTAMP DEFAULT NOW(),
  is_online BOOLEAN DEFAULT false,
  last_seen_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(family_id, user_id)
);

-- 预警记录表
CREATE TABLE public.alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_type TEXT NOT NULL CHECK (alert_type IN ('air_strike', 'artillery', 'conflict', 'curfew', 'chemical', 'other')),
  severity TEXT NOT NULL CHECK (severity IN ('red', 'orange', 'yellow')),
  title TEXT NOT NULL,
  description TEXT,
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  city TEXT,
  country TEXT,
  affected_radius_km INTEGER,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  source TEXT,
  is_verified BOOLEAN DEFAULT false,
  verified_by UUID REFERENCES public.profiles(id),
  verified_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 避难所表
CREATE TABLE public.shelters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  address TEXT,
  latitude DECIMAL(10, 8) NOT NULL,
  longitude DECIMAL(11, 8) NOT NULL,
  city TEXT,
  country TEXT,
  capacity INTEGER,
  current_occupancy INTEGER DEFAULT 0,
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'crowded', 'closed', 'full')),
  has_water BOOLEAN DEFAULT false,
  has_electricity BOOLEAN DEFAULT false,
  has_medical BOOLEAN DEFAULT false,
  has_toilet BOOLEAN DEFAULT false,
  has_rest_area BOOLEAN DEFAULT false,
  phone TEXT,
  opening_hours TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 用户预警设置表
CREATE TABLE public.user_alert_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  monitor_radius_km INTEGER DEFAULT 30,
  alert_air_strike BOOLEAN DEFAULT true,
  alert_artillery BOOLEAN DEFAULT true,
  alert_conflict BOOLEAN DEFAULT true,
  alert_curfew BOOLEAN DEFAULT true,
  push_enabled BOOLEAN DEFAULT true,
  sound_enabled BOOLEAN DEFAULT true,
  vibration_enabled BOOLEAN DEFAULT true,
  flash_enabled BOOLEAN DEFAULT true,
  dnd_start_time TIME,
  dnd_end_time TIME,
  dnd_enabled BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id)
);

-- 邀请记录表
CREATE TABLE public.invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  inviter_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  invite_code TEXT NOT NULL,
  invite_link TEXT,
  invited_phone TEXT,
  invited_email TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'registered', 'rewarded')),
  registered_at TIMESTAMP,
  reward_given BOOLEAN DEFAULT false,
  reward_amount DECIMAL(10, 2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sos_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rescue_pending ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mutual_aid_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mutual_aid_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.family_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.family_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shelters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_alert_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invites ENABLE ROW LEVEL SECURITY;

-- RLS策略：用户只能查看和修改自己的资料
CREATE POLICY "用户查看自己的资料" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "用户修改自己的资料" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- RLS策略：SOS记录
CREATE POLICY "用户查看自己的SOS记录" ON public.sos_records FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "用户创建SOS记录" ON public.sos_records FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "用户更新自己的SOS记录" ON public.sos_records FOR UPDATE USING (auth.uid() = user_id);

-- RLS策略：救援待处理（仅Admin可查看全部）
CREATE POLICY "用户查看自己的救援记录" ON public.rescue_pending FOR SELECT USING (auth.uid() = user_id);

-- RLS策略：互助订阅
CREATE POLICY "用户查看自己的互助订阅" ON public.mutual_aid_subscriptions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "用户管理自己的互助订阅" ON public.mutual_aid_subscriptions FOR ALL USING (auth.uid() = user_id);

-- RLS策略：互助响应
CREATE POLICY "用户查看互助响应" ON public.mutual_aid_responses FOR SELECT USING (auth.uid() = responder_id);
CREATE POLICY "用户创建互助响应" ON public.mutual_aid_responses FOR INSERT WITH CHECK (auth.uid() = responder_id);

-- RLS策略：家庭组
CREATE POLICY "家庭成员查看家庭组" ON public.family_groups FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.family_members WHERE family_id = id AND user_id = auth.uid())
);
CREATE POLICY "管理员管理家庭组" ON public.family_groups FOR ALL USING (auth.uid() = admin_id);

-- RLS策略：家庭成员
CREATE POLICY "家庭成员查看成员列表" ON public.family_members FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.family_members fm WHERE fm.family_id = family_id AND fm.user_id = auth.uid())
);

-- RLS策略：预警（所有人可查看）
CREATE POLICY "所有人可查看预警" ON public.alerts FOR SELECT USING (true);

-- RLS策略：避难所（所有人可查看）
CREATE POLICY "所有人可查看避难所" ON public.shelters FOR SELECT USING (true);

-- RLS策略：用户预警设置
CREATE POLICY "用户管理自己的预警设置" ON public.user_alert_settings FOR ALL USING (auth.uid() = user_id);

-- RLS策略：邀请记录
CREATE POLICY "用户查看自己的邀请" ON public.invites FOR SELECT USING (auth.uid() = inviter_id);
CREATE POLICY "用户创建邀请" ON public.invites FOR INSERT WITH CHECK (auth.uid() = inviter_id);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 为所有表添加更新时间触发器
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_sos_records_updated_at BEFORE UPDATE ON public.sos_records FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_rescue_pending_updated_at BEFORE UPDATE ON public.rescue_pending FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_mutual_aid_subscriptions_updated_at BEFORE UPDATE ON public.mutual_aid_subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_mutual_aid_responses_updated_at BEFORE UPDATE ON public.mutual_aid_responses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_family_groups_updated_at BEFORE UPDATE ON public.family_groups FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_family_members_updated_at BEFORE UPDATE ON public.family_members FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_alerts_updated_at BEFORE UPDATE ON public.alerts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_shelters_updated_at BEFORE UPDATE ON public.shelters FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_user_alert_settings_updated_at BEFORE UPDATE ON public.user_alert_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_invites_updated_at BEFORE UPDATE ON public.invites FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();