-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 模拟预警体验记录表
CREATE TABLE IF NOT EXISTS public.simulation_trials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  started_at TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP NOT NULL,
  is_active BOOLEAN DEFAULT true,
  alert_count INTEGER DEFAULT 0,
  last_alert_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 模拟预警记录表
CREATE TABLE IF NOT EXISTS public.simulation_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trial_id UUID NOT NULL REFERENCES public.simulation_trials(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  alert_type VARCHAR(50) NOT NULL,
  severity VARCHAR(20) NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  city VARCHAR(100),
  country VARCHAR(100),
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  distance DECIMAL(10, 2),
  reliability_score INTEGER DEFAULT 85,
  push_sent BOOLEAN DEFAULT false,
  sms_sent BOOLEAN DEFAULT false,
  acknowledged BOOLEAN DEFAULT false,
  acknowledged_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 模拟预警通知日志表（双向并行记录）
CREATE TABLE IF NOT EXISTS public.simulation_notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_id UUID NOT NULL REFERENCES public.simulation_alerts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  channel VARCHAR(20) NOT NULL, -- 'push', 'sms', 'in_app'
  status VARCHAR(20) NOT NULL, -- 'pending', 'sent', 'delivered', 'failed'
  sent_at TIMESTAMP,
  delivered_at TIMESTAMP,
  error_message TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE public.simulation_trials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.simulation_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.simulation_notifications ENABLE ROW LEVEL SECURITY;

-- RLS策略：用户只能查看自己的模拟数据
CREATE POLICY "用户查看自己的体验记录" ON public.simulation_trials
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "用户创建自己的体验记录" ON public.simulation_trials
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "用户更新自己的体验记录" ON public.simulation_trials
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "用户查看自己的模拟预警" ON public.simulation_alerts
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "用户创建自己的模拟预警" ON public.simulation_alerts
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "用户更新自己的模拟预警" ON public.simulation_alerts
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "用户查看自己的通知记录" ON public.simulation_notifications
  FOR SELECT USING (auth.uid() = user_id);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_simulation_trials_user_id ON public.simulation_trials(user_id);
CREATE INDEX IF NOT EXISTS idx_simulation_trials_active ON public.simulation_trials(is_active);
CREATE INDEX IF NOT EXISTS idx_simulation_alerts_trial_id ON public.simulation_alerts(trial_id);
CREATE INDEX IF NOT EXISTS idx_simulation_alerts_user_id ON public.simulation_alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_simulation_notifications_alert_id ON public.simulation_notifications(alert_id);