import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import * as Clipboard from 'expo-clipboard';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen'; import { supabase } from '../lib/supabase'; import { colors, radius, spacing } from '../theme'; import type { RootStackParams } from '../navigation/RootNavigator';
import { checkPassword } from '../lib/password';

type Props = NativeStackScreenProps<RootStackParams, 'AccountSecurity'>;
type Device = { id: string; platform: string; enabled: boolean; last_seen_at: string; created_at: string };
type Factor = { id: string; friendly_name?: string; status: string };

export function AccountSecurityScreen({ navigation }: Props) {
  const [identity, setIdentity] = useState(''); const [emailIdentity, setEmailIdentity] = useState(''); const [currentPassword, setCurrentPassword] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [bindEmail, setBindEmail] = useState(''); const [bindPhone, setBindPhone] = useState(''); const [phoneCode, setPhoneCode] = useState(''); const [phonePending, setPhonePending] = useState(false); const [devices, setDevices] = useState<Device[]>([]); const [factors, setFactors] = useState<Factor[]>([]); const [totpId, setTotpId] = useState(''); const [totpSecret, setTotpSecret] = useState(''); const [totpCode, setTotpCode] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const { data } = await supabase.auth.getUser(); if (!data.user) return; setIdentity(data.user.email || data.user.phone || ''); setEmailIdentity(data.user.email || ''); const [tokens, mfa] = await Promise.all([supabase.from('device_tokens').select('id,platform,enabled,last_seen_at,created_at').eq('user_id', data.user.id).order('last_seen_at', { ascending: false }), supabase.auth.mfa.listFactors()]); setDevices((tokens.data || []) as Device[]); setFactors((mfa.data?.totp || []) as Factor[]); }, []);
  useEffect(() => { void load(); }, [load]);
  const updatePassword = async () => { const checked = checkPassword(password); if (!checked.valid) return Alert.alert('密码不符合要求', checked.message); if (password !== confirmPassword) return Alert.alert('密码不一致', '请重新确认新密码'); setBusy(true); if (emailIdentity) { const verify = await supabase.auth.signInWithPassword({ email: emailIdentity, password: currentPassword }); if (verify.error) { setBusy(false); return Alert.alert('当前密码错误', '验证当前密码失败，未做任何修改'); } } const { error } = await supabase.auth.updateUser({ password }); setBusy(false); if (error) Alert.alert('修改失败', error.message); else { setCurrentPassword(''); setPassword(''); setConfirmPassword(''); Alert.alert('修改成功', '新密码已生效'); } };
  const changeEmail = async () => { if (!/^\S+@\S+\.\S+$/.test(bindEmail.trim())) return Alert.alert('邮箱无效'); setBusy(true); const { error } = await supabase.auth.updateUser({ email: bindEmail.trim().toLowerCase() }); setBusy(false); Alert.alert(error ? '绑定失败' : '确认邮件已发送', error?.message || '请分别按邮件提示确认新邮箱，确认后才会生效。'); };
  const changePhone = async () => { if (!/^\+\d{7,15}$/.test(bindPhone)) return Alert.alert('手机号无效', '请输入带国际区号的号码，例如 +8613800000000'); setBusy(true); const { error } = await supabase.auth.updateUser({ phone: bindPhone }); setBusy(false); if (error) Alert.alert('验证码发送失败', error.message); else { setPhonePending(true); Alert.alert('验证码已发送'); } };
  const verifyPhone = async () => { setBusy(true); const { error } = await supabase.auth.verifyOtp({ phone: bindPhone, token: phoneCode, type: 'phone_change' }); setBusy(false); if (error) Alert.alert('验证失败', error.message); else { setPhonePending(false); setPhoneCode(''); await load(); Alert.alert('手机号已绑定'); } };
  const enrollTotp = async () => { setBusy(true); const { data, error } = await supabase.auth.mfa.enroll({ factorType: 'totp', friendlyName: 'WarRescue Authenticator' }); setBusy(false); if (error) return Alert.alert('启用失败', error.message); setTotpId(data.id); setTotpSecret(data.totp.secret); Alert.alert('验证器密钥已生成', '复制密钥到任意身份验证器，然后输入6位动态码完成启用。'); };
  const verifyTotp = async () => { setBusy(true); const { error } = await supabase.auth.mfa.challengeAndVerify({ factorId: totpId, code: totpCode }); setBusy(false); if (error) Alert.alert('验证失败', error.message); else { setTotpId(''); setTotpSecret(''); setTotpCode(''); await load(); Alert.alert('两步验证已启用'); } };
  const removeTotp = (factor: Factor) => Alert.alert('关闭两步验证', '确认移除此验证器？', [{ text: '取消', style: 'cancel' }, { text: '移除', style: 'destructive', onPress: async () => { const { error } = await supabase.auth.mfa.unenroll({ factorId: factor.id }); if (error) Alert.alert('移除失败', error.message); else await load(); } }]);
  const removeDevice = (device: Device) => Alert.alert('移除设备', '该设备将不再接收推送；如需使登录会话失效，请同时退出所有设备。', [{ text: '取消', style: 'cancel' }, { text: '移除', style: 'destructive', onPress: async () => { await supabase.from('device_tokens').delete().eq('id', device.id); await load(); } }]);
  const logoutAll = () => Alert.alert('退出所有设备', '其他设备上的登录状态也会失效。', [{ text: '取消', style: 'cancel' }, { text: '退出', style: 'destructive', onPress: () => void supabase.auth.signOut({ scope: 'global' }) }]);
  const deleteAccount = () => Alert.alert('永久注销账号', '此操作会删除账号和关联数据，无法撤销。', [{ text: '取消', style: 'cancel' }, { text: '永久删除', style: 'destructive', onPress: async () => { setBusy(true); const { data, error } = await supabase.functions.invoke('delete-account'); setBusy(false); if (error || !data?.success) Alert.alert('注销失败', data?.error || error?.message || '请联系客服'); else await supabase.auth.signOut(); } }]);
  return <Screen title="账号安全" subtitle={identity} action={<Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>返回</Text></Pressable>}>
    <View style={styles.card}><Text style={styles.title}>修改密码</Text>{emailIdentity ? <TextInput style={styles.input} value={currentPassword} onChangeText={setCurrentPassword} placeholder="当前密码" placeholderTextColor={colors.muted} secureTextEntry autoCapitalize="none" /> : <Text style={styles.body}>手机号验证码账号无需验证旧密码。</Text>}<TextInput style={styles.input} value={password} onChangeText={(value) => setPassword(value.slice(0, 128))} placeholder="新密码（至少8位，包含字母和数字）" placeholderTextColor={colors.muted} secureTextEntry autoCapitalize="none" autoCorrect={false} /><Text style={styles.body}>{checkPassword(password).message}</Text><TextInput style={styles.input} value={confirmPassword} onChangeText={(value) => setConfirmPassword(value.slice(0, 128))} placeholder="再次输入新密码" placeholderTextColor={colors.muted} secureTextEntry autoCapitalize="none" autoCorrect={false} /><Pressable style={styles.primary} onPress={() => void updatePassword()} disabled={busy}>{busy ? <ActivityIndicator color={colors.white} /> : <Text style={styles.primaryText}>保存新密码</Text>}</Pressable></View>
    <View style={styles.card}><Text style={styles.title}>绑定邮箱</Text><TextInput style={styles.input} value={bindEmail} onChangeText={setBindEmail} placeholder="新的邮箱地址" placeholderTextColor={colors.muted} autoCapitalize="none" keyboardType="email-address" /><Pressable style={styles.outline} onPress={() => void changeEmail()}><Text style={styles.outlineText}>发送邮箱确认</Text></Pressable></View>
    <View style={styles.card}><Text style={styles.title}>绑定手机号</Text><TextInput style={styles.input} value={bindPhone} onChangeText={setBindPhone} placeholder="+8613800000000" placeholderTextColor={colors.muted} keyboardType="phone-pad" /><Pressable style={styles.outline} onPress={() => void changePhone()}><Text style={styles.outlineText}>发送短信验证码</Text></Pressable>{phonePending ? <><TextInput style={styles.input} value={phoneCode} onChangeText={(value) => setPhoneCode(value.replace(/\D/g, '').slice(0, 6))} placeholder="6位验证码" placeholderTextColor={colors.muted} keyboardType="number-pad" /><Pressable style={styles.primary} onPress={() => void verifyPhone()}><Text style={styles.primaryText}>确认绑定</Text></Pressable></> : null}</View>
    <View style={styles.card}><Text style={styles.title}>两步验证</Text>{factors.map((factor) => <View key={factor.id} style={styles.row}><View><Text style={styles.rowTitle}>{factor.friendly_name || '身份验证器'}</Text><Text style={styles.rowMeta}>{factor.status === 'verified' ? '已启用' : factor.status}</Text></View><Pressable onPress={() => removeTotp(factor)}><Text style={styles.remove}>移除</Text></Pressable></View>)}{totpSecret ? <><Text style={styles.secret}>{totpSecret}</Text><Pressable onPress={() => void Clipboard.setStringAsync(totpSecret)}><Text style={styles.link}>复制验证器密钥</Text></Pressable><TextInput style={styles.input} value={totpCode} onChangeText={(value) => setTotpCode(value.replace(/\D/g, '').slice(0, 6))} placeholder="验证器6位动态码" placeholderTextColor={colors.muted} keyboardType="number-pad" /><Pressable style={styles.primary} onPress={() => void verifyTotp()}><Text style={styles.primaryText}>验证并启用</Text></Pressable></> : <Pressable style={styles.outline} onPress={() => void enrollTotp()}><Text style={styles.outlineText}>添加身份验证器</Text></Pressable>}</View>
    <View style={styles.card}><Text style={styles.title}>登录设备与推送端点</Text>{devices.map((device) => <View key={device.id} style={styles.row}><View><Text style={styles.rowTitle}>{device.platform.toUpperCase()} 设备</Text><Text style={styles.rowMeta}>最后活动 {new Date(device.last_seen_at).toLocaleString('zh-CN')}</Text></View><Pressable onPress={() => removeDevice(device)}><Text style={styles.remove}>移除</Text></Pressable></View>)}{!devices.length ? <Text style={styles.body}>暂无已登记推送设备。</Text> : null}<Pressable style={styles.outline} onPress={logoutAll}><Text style={styles.outlineText}>退出所有设备</Text></Pressable></View>
    <View style={[styles.card, styles.dangerCard]}><Text style={styles.title}>注销账号</Text><Text style={styles.body}>永久删除账号、资料以及法律允许删除的关联记录。</Text><Pressable style={styles.delete} onPress={deleteAccount} disabled={busy}><Text style={styles.deleteText}>永久注销账号</Text></Pressable></View>
  </Screen>;
}
const styles = StyleSheet.create({ back: { color: colors.info, fontWeight: '800' }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.lg, gap: spacing.md }, dangerCard: { borderColor: '#EF444466' }, title: { color: colors.text, fontSize: 17, fontWeight: '900' }, body: { color: colors.muted, lineHeight: 21 }, input: { height: 52, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border, color: colors.text, backgroundColor: colors.background, paddingHorizontal: spacing.md }, primary: { height: 50, borderRadius: radius.sm, backgroundColor: colors.danger, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: colors.white, fontWeight: '900' }, outline: { height: 48, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.warning, alignItems: 'center', justifyContent: 'center' }, outlineText: { color: colors.warning, fontWeight: '800' }, delete: { height: 48, borderRadius: radius.sm, backgroundColor: '#7F1D1D88', alignItems: 'center', justifyContent: 'center' }, deleteText: { color: '#FCA5A5', fontWeight: '900' }, row: { minHeight: 56, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth }, rowTitle: { color: colors.text, fontWeight: '800' }, rowMeta: { color: colors.muted, fontSize: 11, marginTop: 4 }, remove: { color: colors.danger, fontWeight: '800' }, secret: { color: colors.warning, fontWeight: '900', letterSpacing: 2, textAlign: 'center' }, link: { color: colors.info, fontWeight: '800', textAlign: 'center' } });
