import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import * as Clipboard from 'expo-clipboard';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen'; import { supabase } from '../lib/supabase'; import { colors, radius, spacing } from '../theme'; import type { RootStackParams } from '../navigation/RootNavigator';

type Props = NativeStackScreenProps<RootStackParams, 'AccountSecurity'>;
type Device = { id: string; platform: string; enabled: boolean; last_seen_at: string; created_at: string };
type Factor = { id: string; friendly_name?: string; status: string };

export function AccountSecurityScreen({ navigation }: Props) {
  const [identity, setIdentity] = useState(''); const [emailIdentity, setEmailIdentity] = useState(''); const [currentPassword, setCurrentPassword] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [bindEmail, setBindEmail] = useState(''); const [bindPhone, setBindPhone] = useState(''); const [phoneCode, setPhoneCode] = useState(''); const [phonePending, setPhonePending] = useState(false); const [devices, setDevices] = useState<Device[]>([]); const [factors, setFactors] = useState<Factor[]>([]); const [totpId, setTotpId] = useState(''); const [totpSecret, setTotpSecret] = useState(''); const [totpCode, setTotpCode] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const { data } = await supabase.auth.getUser(); if (!data.user) return; setIdentity(data.user.email || data.user.phone || ''); setEmailIdentity(data.user.email || ''); const [tokens, mfa] = await Promise.all([supabase.from('device_tokens').select('id,platform,enabled,last_seen_at,created_at').eq('user_id', data.user.id).order('last_seen_at', { ascending: false }), supabase.auth.mfa.listFactors()]); setDevices((tokens.data || []) as Device[]); setFactors((mfa.data?.totp || []) as Factor[]); }, []);
  useEffect(() => { void load(); }, [load]);
  const updatePassword = async () => { if (password.length < 8) return Alert.alert('????', '???????8?'); if (password !== confirmPassword) return Alert.alert('?????', '????????'); setBusy(true); if (emailIdentity) { const verify = await supabase.auth.signInWithPassword({ email: emailIdentity, password: currentPassword }); if (verify.error) { setBusy(false); return Alert.alert('??????', '???????????????'); } } const { error } = await supabase.auth.updateUser({ password }); setBusy(false); if (error) Alert.alert('????', error.message); else { setCurrentPassword(''); setPassword(''); setConfirmPassword(''); Alert.alert('????', '??????'); } };
  const changeEmail = async () => { if (!/^\S+@\S+\.\S+$/.test(bindEmail.trim())) return Alert.alert('????'); setBusy(true); const { error } = await supabase.auth.updateUser({ email: bindEmail.trim().toLowerCase() }); setBusy(false); Alert.alert(error ? '????' : '???????', error?.message || '??????????????????????'); };
  const changePhone = async () => { if (!/^\+\d{7,15}$/.test(bindPhone)) return Alert.alert('?????', '?????????????? +8613800000000'); setBusy(true); const { error } = await supabase.auth.updateUser({ phone: bindPhone }); setBusy(false); if (error) Alert.alert('???????', error.message); else { setPhonePending(true); Alert.alert('??????'); } };
  const verifyPhone = async () => { setBusy(true); const { error } = await supabase.auth.verifyOtp({ phone: bindPhone, token: phoneCode, type: 'phone_change' }); setBusy(false); if (error) Alert.alert('????', error.message); else { setPhonePending(false); setPhoneCode(''); await load(); Alert.alert('??????'); } };
  const enrollTotp = async () => { setBusy(true); const { data, error } = await supabase.auth.mfa.enroll({ factorType: 'totp', friendlyName: 'WarRescue Authenticator' }); setBusy(false); if (error) return Alert.alert('????', error.message); setTotpId(data.id); setTotpSecret(data.totp.secret); Alert.alert('????????', '?????????????????6?????????'); };
  const verifyTotp = async () => { setBusy(true); const { error } = await supabase.auth.mfa.challengeAndVerify({ factorId: totpId, code: totpCode }); setBusy(false); if (error) Alert.alert('????', error.message); else { setTotpId(''); setTotpSecret(''); setTotpCode(''); await load(); Alert.alert('???????'); } };
  const removeTotp = (factor: Factor) => Alert.alert('??????', '?????????', [{ text: '??', style: 'cancel' }, { text: '??', style: 'destructive', onPress: async () => { const { error } = await supabase.auth.mfa.unenroll({ factorId: factor.id }); if (error) Alert.alert('????', error.message); else await load(); } }]);
  const removeDevice = (device: Device) => Alert.alert('????', '???????????????????????????????', [{ text: '??', style: 'cancel' }, { text: '??', style: 'destructive', onPress: async () => { await supabase.from('device_tokens').delete().eq('id', device.id); await load(); } }]);
  const logoutAll = () => Alert.alert('??????', '???????????????', [{ text: '??', style: 'cancel' }, { text: '??', style: 'destructive', onPress: () => void supabase.auth.signOut({ scope: 'global' }) }]);
  const deleteAccount = () => Alert.alert('??????', '???????????????????', [{ text: '??', style: 'cancel' }, { text: '????', style: 'destructive', onPress: async () => { setBusy(true); const { data, error } = await supabase.functions.invoke('delete-account'); setBusy(false); if (error || !data?.success) Alert.alert('????', data?.error || error?.message || '?????'); else await supabase.auth.signOut(); } }]);
  return <Screen title="????" subtitle={identity} action={<Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>??</Text></Pressable>}>
    <View style={styles.card}><Text style={styles.title}>????</Text>{emailIdentity ? <TextInput style={styles.input} value={currentPassword} onChangeText={setCurrentPassword} placeholder="????" placeholderTextColor={colors.muted} secureTextEntry /> : <Text style={styles.body}>????????????????</Text>}<TextInput style={styles.input} value={password} onChangeText={setPassword} placeholder="??????8??" placeholderTextColor={colors.muted} secureTextEntry /><TextInput style={styles.input} value={confirmPassword} onChangeText={setConfirmPassword} placeholder="???????" placeholderTextColor={colors.muted} secureTextEntry /><Pressable style={styles.primary} onPress={() => void updatePassword()} disabled={busy}>{busy ? <ActivityIndicator color={colors.white} /> : <Text style={styles.primaryText}>?????</Text>}</Pressable></View>
    <View style={styles.card}><Text style={styles.title}>????</Text><TextInput style={styles.input} value={bindEmail} onChangeText={setBindEmail} placeholder="??????" placeholderTextColor={colors.muted} autoCapitalize="none" keyboardType="email-address" /><Pressable style={styles.outline} onPress={() => void changeEmail()}><Text style={styles.outlineText}>??????</Text></Pressable></View>
    <View style={styles.card}><Text style={styles.title}>?????</Text><TextInput style={styles.input} value={bindPhone} onChangeText={setBindPhone} placeholder="+8613800000000" placeholderTextColor={colors.muted} keyboardType="phone-pad" /><Pressable style={styles.outline} onPress={() => void changePhone()}><Text style={styles.outlineText}>???????</Text></Pressable>{phonePending ? <><TextInput style={styles.input} value={phoneCode} onChangeText={(value) => setPhoneCode(value.replace(/\D/g, '').slice(0, 6))} placeholder="6????" placeholderTextColor={colors.muted} keyboardType="number-pad" /><Pressable style={styles.primary} onPress={() => void verifyPhone()}><Text style={styles.primaryText}>????</Text></Pressable></> : null}</View>
    <View style={styles.card}><Text style={styles.title}>????</Text>{factors.map((factor) => <View key={factor.id} style={styles.row}><View><Text style={styles.rowTitle}>{factor.friendly_name || '?????'}</Text><Text style={styles.rowMeta}>{factor.status === 'verified' ? '???' : factor.status}</Text></View><Pressable onPress={() => removeTotp(factor)}><Text style={styles.remove}>??</Text></Pressable></View>)}{totpSecret ? <><Text style={styles.secret}>{totpSecret}</Text><Pressable onPress={() => void Clipboard.setStringAsync(totpSecret)}><Text style={styles.link}>???????</Text></Pressable><TextInput style={styles.input} value={totpCode} onChangeText={(value) => setTotpCode(value.replace(/\D/g, '').slice(0, 6))} placeholder="???6????" placeholderTextColor={colors.muted} keyboardType="number-pad" /><Pressable style={styles.primary} onPress={() => void verifyTotp()}><Text style={styles.primaryText}>?????</Text></Pressable></> : <Pressable style={styles.outline} onPress={() => void enrollTotp()}><Text style={styles.outlineText}>???????</Text></Pressable>}</View>
    <View style={styles.card}><Text style={styles.title}>?????????</Text>{devices.map((device) => <View key={device.id} style={styles.row}><View><Text style={styles.rowTitle}>{device.platform.toUpperCase()} ??</Text><Text style={styles.rowMeta}>???? {new Date(device.last_seen_at).toLocaleString('zh-CN')}</Text></View><Pressable onPress={() => removeDevice(device)}><Text style={styles.remove}>??</Text></Pressable></View>)}{!devices.length ? <Text style={styles.body}>??????????</Text> : null}<Pressable style={styles.outline} onPress={logoutAll}><Text style={styles.outlineText}>??????</Text></Pressable></View>
    <View style={[styles.card, styles.dangerCard]}><Text style={styles.title}>????</Text><Text style={styles.body}>???????????????????????</Text><Pressable style={styles.delete} onPress={deleteAccount} disabled={busy}><Text style={styles.deleteText}>??????</Text></Pressable></View>
  </Screen>;
}
const styles = StyleSheet.create({ back: { color: colors.info, fontWeight: '800' }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.lg, gap: spacing.md }, dangerCard: { borderColor: '#EF444466' }, title: { color: colors.text, fontSize: 17, fontWeight: '900' }, body: { color: colors.muted, lineHeight: 21 }, input: { height: 52, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border, color: colors.text, backgroundColor: colors.background, paddingHorizontal: spacing.md }, primary: { height: 50, borderRadius: radius.sm, backgroundColor: colors.danger, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: colors.white, fontWeight: '900' }, outline: { height: 48, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.warning, alignItems: 'center', justifyContent: 'center' }, outlineText: { color: colors.warning, fontWeight: '800' }, delete: { height: 48, borderRadius: radius.sm, backgroundColor: '#7F1D1D88', alignItems: 'center', justifyContent: 'center' }, deleteText: { color: '#FCA5A5', fontWeight: '900' }, row: { minHeight: 56, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth }, rowTitle: { color: colors.text, fontWeight: '800' }, rowMeta: { color: colors.muted, fontSize: 11, marginTop: 4 }, remove: { color: colors.danger, fontWeight: '800' }, secret: { color: colors.warning, fontWeight: '900', letterSpacing: 2, textAlign: 'center' }, link: { color: colors.info, fontWeight: '800', textAlign: 'center' } });
