import { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useFocusEffect } from '@react-navigation/native';
import { Screen } from '../components/Screen';
import { supabase } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';
import type { RootStackParams } from '../navigation/RootNavigator';
type Props = NativeStackScreenProps<RootStackParams, 'AlertSettings'>;
type Settings = { monitor_radius_km: number; city: string; country: string; min_severity: 'yellow' | 'orange' | 'red'; alert_air_strike: boolean; alert_artillery: boolean; alert_conflict: boolean; alert_curfew: boolean; push_enabled: boolean; sound_enabled: boolean; vibration_enabled: boolean; flash_enabled: boolean; dnd_enabled: boolean; precise_location_enabled: boolean; background_monitor_enabled: boolean };
const defaults: Settings = { monitor_radius_km: 30, city: '', country: '', min_severity: 'yellow', alert_air_strike: true, alert_artillery: true, alert_conflict: true, alert_curfew: true, push_enabled: true, sound_enabled: true, vibration_enabled: true, flash_enabled: true, dnd_enabled: false, precise_location_enabled: true, background_monitor_enabled: true };
export function AlertSettingsScreen({ navigation }: Props) {
  const [form, setForm] = useState(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const { data: auth } = await supabase.auth.getUser(); if (auth.user) { const { data } = await supabase.from('user_alert_settings').select('*').eq('user_id', auth.user.id).maybeSingle(); if (data) setForm({ ...defaults, ...data }); } setLoading(false); }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const toggle = (key: keyof Settings) => setForm((current) => ({ ...current, [key]: !current[key] }));
  const save = async () => { setSaving(true); const { data: auth } = await supabase.auth.getUser(); const result = auth.user ? await supabase.from('user_alert_settings').upsert({ user_id: auth.user.id, ...form }, { onConflict: 'user_id' }) : { error: new Error('?????') }; setSaving(false); Alert.alert(result.error ? '????' : '?????', result.error?.message || '????????????'); };
  if (loading) return <View style={styles.loading}><ActivityIndicator color={colors.danger} size="large" /></View>;
  return <Screen title="????" subtitle="?????????" action={<Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>??</Text></Pressable>}>
    <View style={styles.card}><Text style={styles.title}>????</Text><Text style={styles.radius}>{form.monitor_radius_km} km</Text><View style={styles.options}>{[5, 10, 30, 50, 100].map((value) => <Pressable key={value} style={[styles.range, form.monitor_radius_km === value && styles.rangeActive]} onPress={() => setForm((current) => ({ ...current, monitor_radius_km: value }))}><Text style={[styles.rangeText, form.monitor_radius_km === value && styles.rangeTextActive]}>{value}</Text></Pressable>)}</View></View>
    <Pressable style={styles.card} onPress={() => navigation.navigate('CitySelect')}><Text style={styles.title}>????</Text><Text style={styles.cityValue}>{[form.city, form.country].filter(Boolean).join(' ? ') || '????????'} ?</Text></Pressable>
    <View style={styles.card}><Text style={styles.title}>??????</Text><View style={styles.options}>{(['yellow', 'orange', 'red'] as const).map((value) => <Pressable key={value} style={[styles.range, form.min_severity === value && styles.rangeActive]} onPress={() => setForm((current) => ({ ...current, min_severity: value }))}><Text style={[styles.rangeText, form.min_severity === value && styles.rangeTextActive]}>{value === 'yellow' ? '??+' : value === 'orange' ? '??+' : '???'}</Text></Pressable>)}</View></View>
    <View style={styles.card}><Text style={styles.title}>????</Text><Toggle label="?????" value={form.alert_air_strike} onChange={() => toggle('alert_air_strike')} /><Toggle label="??????" value={form.alert_artillery} onChange={() => toggle('alert_artillery')} /><Toggle label="????" value={form.alert_conflict} onChange={() => toggle('alert_conflict')} /><Toggle label="?????" value={form.alert_curfew} onChange={() => toggle('alert_curfew')} /></View>
    <View style={styles.card}><Text style={styles.title}>????</Text><Toggle label="????" value={form.push_enabled} onChange={() => toggle('push_enabled')} /><Toggle label="??" value={form.sound_enabled} onChange={() => toggle('sound_enabled')} /><Toggle label="??" value={form.vibration_enabled} onChange={() => toggle('vibration_enabled')} /><Toggle label="?????" value={form.flash_enabled} onChange={() => toggle('flash_enabled')} /><Toggle label="?????" value={form.dnd_enabled} onChange={() => toggle('dnd_enabled')} /></View>
    <View style={styles.card}><Text style={styles.title}>????</Text><Toggle label="????" value={form.precise_location_enabled} onChange={() => toggle('precise_location_enabled')} /><Toggle label="??????" value={form.background_monitor_enabled} onChange={() => toggle('background_monitor_enabled')} /><Pressable onPress={() => navigation.navigate('MonitoredLocations')}><Text style={styles.cityValue}>??????? ?</Text></Pressable></View>
    <Pressable style={styles.save} onPress={save} disabled={saving}>{saving ? <ActivityIndicator color={colors.white} /> : <Text style={styles.saveText}>???????</Text>}</Pressable>
  </Screen>;
}
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: () => void }) { return <View style={styles.toggle}><Text style={styles.toggleLabel}>{label}</Text><Switch value={value} onValueChange={onChange} trackColor={{ false: colors.border, true: colors.dangerDark }} thumbColor={value ? colors.danger : colors.muted} /></View>; }
const styles = StyleSheet.create({ loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, back: { color: colors.info, fontWeight: '800' }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.lg, gap: spacing.sm }, title: { color: colors.text, fontSize: 17, fontWeight: '900' }, cityValue: { color: colors.info, fontWeight: '800', marginTop: spacing.sm }, radius: { color: colors.danger, fontSize: 30, fontWeight: '900' }, options: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, range: { minWidth: 48, paddingHorizontal: spacing.sm, height: 40, borderRadius: radius.sm, backgroundColor: colors.surfaceRaised, alignItems: 'center', justifyContent: 'center' }, rangeActive: { backgroundColor: colors.danger }, rangeText: { color: colors.muted, fontWeight: '800' }, rangeTextActive: { color: colors.white }, toggle: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth }, toggleLabel: { color: '#E2E8F0', fontWeight: '700' }, save: { height: 52, borderRadius: radius.md, backgroundColor: colors.danger, alignItems: 'center', justifyContent: 'center' }, saveText: { color: colors.white, fontWeight: '900' } });
