import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen';
import { supabase } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';
import type { RootStackParams } from '../navigation/RootNavigator';
type Props = NativeStackScreenProps<RootStackParams, 'CitySelect'>;
type City = { city: string; country: string };
const common: City[] = [{ city: 'Kyiv', country: 'Ukraine' }, { city: 'Kharkiv', country: 'Ukraine' }, { city: 'Odesa', country: 'Ukraine' }, { city: 'Dnipro', country: 'Ukraine' }, { city: 'Lviv', country: 'Ukraine' }, { city: 'Gaza', country: 'Palestine' }, { city: 'Jerusalem', country: 'Israel' }, { city: 'Tel Aviv', country: 'Israel' }, { city: 'Beirut', country: 'Lebanon' }, { city: 'Damascus', country: 'Syria' }, { city: 'Aleppo', country: 'Syria' }, { city: 'Baghdad', country: 'Iraq' }, { city: 'Erbil', country: 'Iraq' }, { city: 'Sanaa', country: 'Yemen' }, { city: 'Aden', country: 'Yemen' }, { city: 'Khartoum', country: 'Sudan' }];
export function CitySelectScreen({ navigation }: Props) {
  const [query, setQuery] = useState(''); const [cities, setCities] = useState<City[]>(common); const [recent, setRecent] = useState<City[]>([]); const [selected, setSelected] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { void (async () => { const [alerts, shelters, saved, auth] = await Promise.all([supabase.from('alerts').select('city,country').not('city', 'is', null).limit(500), supabase.from('shelters').select('city,country').not('city', 'is', null).limit(500), AsyncStorage.getItem('recent-cities'), supabase.auth.getUser()]); const combined = [...common, ...(alerts.data || []), ...(shelters.data || [])].filter((item): item is City => !!item.city && !!item.country); setCities([...new Map(combined.map((item) => [`${item.country}|${item.city}`, item])).values()].sort((a, b) => a.country.localeCompare(b.country) || a.city.localeCompare(b.city))); if (saved) setRecent(JSON.parse(saved)); if (auth.data.user) { const { data } = await supabase.from('profiles').select('city,country').eq('id', auth.data.user.id).maybeSingle(); setSelected(`${data?.country || ''}|${data?.city || ''}`); } })(); }, []);
  const filtered = useMemo(() => { const value = query.trim().toLowerCase(); return value ? cities.filter((item) => `${item.city} ${item.country}`.toLowerCase().includes(value)) : cities; }, [cities, query]);
  const choose = async (item: City) => { setBusy(true); const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return; const [profile, settings] = await Promise.all([supabase.from('profiles').update({ city: item.city, country: item.country }).eq('id', auth.user.id), supabase.from('user_alert_settings').upsert({ user_id: auth.user.id, city: item.city, country: item.country }, { onConflict: 'user_id' })]); setBusy(false); if (profile.error || settings.error) return Alert.alert('保存失败', profile.error?.message || settings.error?.message); const next = [item, ...recent.filter((value) => value.city !== item.city || value.country !== item.country)].slice(0, 5); await AsyncStorage.setItem('recent-cities', JSON.stringify(next)); setSelected(`${item.country}|${item.city}`); navigation.goBack(); };
  const groups = useMemo(() => Object.entries(filtered.reduce<Record<string, City[]>>((acc, item) => { (acc[item.country] ||= []).push(item); return acc; }, {})), [filtered]);
  return <Screen title="选择城市" subtitle="同步常驻城市和预警监控地区" action={<Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>返回</Text></Pressable>}>
    <TextInput style={styles.search} value={query} onChangeText={setQuery} placeholder="搜索城市或国家" placeholderTextColor={colors.muted} autoCapitalize="words" />
    {recent.length && !query ? <View style={styles.card}><Text style={styles.section}>最近选择</Text><View style={styles.quick}>{recent.map((item) => <Pressable key={`${item.country}-${item.city}`} style={styles.chip} onPress={() => void choose(item)}><Text style={styles.chipText}>{item.city}</Text></Pressable>)}</View></View> : null}
    {groups.map(([country, items]) => <View key={country} style={styles.card}><Text style={styles.section}>{country}</Text>{items.map((item) => { const key = `${item.country}|${item.city}`; return <Pressable key={key} style={styles.row} onPress={() => void choose(item)}><Text style={styles.city}>{item.city}</Text><Text style={selected === key ? styles.selected : styles.country}>{selected === key ? '✓ 已选择' : item.country}</Text></Pressable>; })}</View>)}
    {busy ? <ActivityIndicator color={colors.info} /> : null}
  </Screen>;
}
const styles = StyleSheet.create({ back: { color: colors.info, fontWeight: '800' }, search: { height: 52, borderRadius: radius.md, borderColor: colors.border, borderWidth: 1, backgroundColor: colors.surface, color: colors.text, paddingHorizontal: spacing.md, fontSize: 16 }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.md }, section: { color: colors.text, fontSize: 17, fontWeight: '900', marginBottom: spacing.sm }, quick: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, chip: { backgroundColor: '#0C4A6E', borderRadius: radius.round, paddingHorizontal: 13, paddingVertical: 8 }, chipText: { color: colors.info, fontWeight: '800' }, row: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth }, city: { color: colors.text, fontWeight: '800' }, country: { color: colors.muted, fontSize: 12 }, selected: { color: colors.safe, fontWeight: '800', fontSize: 12 } });
