import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Linking, Pressable, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import * as Location from 'expo-location';
import * as Battery from 'expo-battery';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen';
import { supabase } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';
import type { RootStackParams } from '../navigation/RootNavigator';
type Props = NativeStackScreenProps<RootStackParams, 'Family'>;
type Member = { id: string; user_id: string; role: 'admin' | 'member'; is_online: boolean; last_seen_at?: string | null; latitude?: number | null; longitude?: number | null; battery_level?: number | null; safety_status?: 'safe' | 'attention' | 'danger' | 'unknown'; profiles?: { nickname?: string | null; city?: string | null; country?: string | null } | null };
type Family = { id: string; name: string; invite_code: string; max_members: number; location_sharing_enabled: boolean; sos_sync_enabled: boolean; alert_sync_enabled: boolean; members: Member[] };
export function FamilyScreen({ navigation }: Props) {
  const [userId, setUserId] = useState(''); const [family, setFamily] = useState<Family | null>(null); const [name, setName] = useState('我的家庭'); const [inviteCode, setInviteCode] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const invoke = useCallback(async (action: string, body: Record<string, unknown> = {}) => supabase.functions.invoke('family-service', { body: { action, userId, ...body } }), [userId]);
  const load = useCallback(async (id?: string) => { const actualId = id || userId; if (!actualId) return; const { data, error } = await supabase.functions.invoke('family-service', { body: { action: 'get-family', userId: actualId } }); if (error || data?.error) Alert.alert('家庭数据加载失败', data?.error || error?.message); else setFamily(data?.family || null); setLoading(false); }, [userId]);
  useEffect(() => { void supabase.auth.getUser().then(({ data }) => { if (data.user) { setUserId(data.user.id); void load(data.user.id); } else setLoading(false); }); }, [load]);
  useEffect(() => { if (!family?.location_sharing_enabled || !userId) return; void (async () => { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') return; const [location, battery] = await Promise.all([Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }), Battery.getBatteryLevelAsync()]); await invoke('update-location', { latitude: location.coords.latitude, longitude: location.coords.longitude, accuracy: location.coords.accuracy, batteryLevel: battery >= 0 ? Math.round(battery * 100) : null, safetyStatus: 'safe' }); })(); }, [family?.location_sharing_enabled, invoke, userId]);
  const me = useMemo(() => family?.members.find((member) => member.user_id === userId), [family, userId]); const isAdmin = me?.role === 'admin';
  const run = async (action: string, body: Record<string, unknown>, success: string) => { setBusy(true); const { data, error } = await invoke(action, body); setBusy(false); if (error || data?.error || data?.success === false) Alert.alert('操作失败', data?.error || error?.message || '请稍后重试'); else { Alert.alert(success); await load(); } };
  const updateSetting = async (key: 'location_sharing_enabled' | 'sos_sync_enabled' | 'alert_sync_enabled', value: boolean) => { if (!family) return; await run('update-settings', { familyId: family.id, settings: { [key]: value } }, '设置已同步'); };
  if (loading) return <View style={styles.loading}><ActivityIndicator color={colors.info} size="large" /></View>;
  return <Screen title="家庭守护" subtitle="位置、预警与SOS联动" action={<Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>返回</Text></Pressable>} refreshing={busy} onRefresh={() => void load()}>
    {!family ? <><View style={styles.card}><Text style={styles.title}>创建家庭</Text><Text style={styles.body}>创建后会生成8位邀请码，最多可添加6位成员。</Text><TextInput style={styles.input} value={name} onChangeText={setName} placeholder="家庭名称" placeholderTextColor={colors.muted} /><Pressable style={styles.primary} onPress={() => void run('create-family', { name }, '家庭已创建')} disabled={busy}><Text style={styles.primaryText}>创建家庭</Text></Pressable></View><View style={styles.card}><Text style={styles.title}>加入家庭</Text><TextInput style={styles.input} value={inviteCode} onChangeText={(v) => setInviteCode(v.toUpperCase().slice(0, 8))} placeholder="输入8位邀请码" placeholderTextColor={colors.muted} autoCapitalize="characters" /><Pressable style={styles.secondary} onPress={() => void run('join-family', { inviteCode }, '已加入家庭')} disabled={busy}><Text style={styles.secondaryText}>加入家庭</Text></Pressable></View></> : <>
      <View style={styles.hero}><Text style={styles.familyName}>{family.name}</Text><Text style={styles.code}>邀请码 {family.invite_code}</Text><View style={styles.stats}><Stat value={family.members.length} label="成员" /><Stat value={family.members.filter((m) => m.is_online).length} label="在线" /><Stat value={Math.max(0, family.max_members - family.members.length)} label="空位" /></View></View>
      <View style={styles.card}><Text style={styles.title}>家庭成员</Text>{family.members.map((member) => <View key={member.id} style={styles.member}><View style={[styles.online, !member.is_online && styles.offline]} /><View style={styles.memberBody}><Text style={styles.memberName}>{member.profiles?.nickname || (member.user_id === userId ? '我' : '家庭成员')} <Text style={styles.role}>{member.role === 'admin' ? '管理员' : '成员'}</Text></Text><Text style={styles.memberMeta}>{member.is_online ? '在线' : member.last_seen_at ? `最后在线 ${new Date(member.last_seen_at).toLocaleString('zh-CN')}` : '离线'}{member.battery_level != null ? ` · 电量 ${member.battery_level}%` : ''} · {safetyLabel(member.safety_status)}</Text></View>{member.latitude != null && member.longitude != null ? <Pressable onPress={() => void Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${member.latitude},${member.longitude}`)}><Text style={styles.locate}>定位</Text></Pressable> : null}{isAdmin && member.user_id !== userId ? <Pressable onPress={() => Alert.alert('成员管理', '请选择操作', [{ text: '取消', style: 'cancel' }, { text: '转让管理员', onPress: () => void run('transfer-admin', { currentAdminId: userId, newAdminId: member.user_id, familyId: family.id }, '管理员已转让') }, { text: '移除成员', style: 'destructive', onPress: () => void run('remove-member', { adminId: userId, memberId: member.id, familyId: family.id }, '成员已移除') }])}><Text style={styles.more}>•••</Text></Pressable> : null}</View>)}</View>
      <View style={styles.card}><Text style={styles.title}>联动设置</Text><Toggle label="共享家庭位置" value={family.location_sharing_enabled} disabled={!isAdmin} onChange={(v) => void updateSetting('location_sharing_enabled', v)} /><Toggle label="一人SOS通知全员" value={family.sos_sync_enabled} disabled={!isAdmin} onChange={(v) => void updateSetting('sos_sync_enabled', v)} /><Toggle label="家庭预警同步" value={family.alert_sync_enabled} disabled={!isAdmin} onChange={(v) => void updateSetting('alert_sync_enabled', v)} /></View>
      <Pressable style={styles.leave} onPress={() => Alert.alert('退出家庭', isAdmin && family.members.length > 1 ? '管理员退出后将自动转让给另一位成员。' : '确定退出当前家庭吗？', [{ text: '取消', style: 'cancel' }, { text: '退出', style: 'destructive', onPress: () => void run('leave-family', { familyId: family.id }, '已退出家庭') }])}><Text style={styles.leaveText}>退出家庭</Text></Pressable>
    </>}
  </Screen>;
}
function Toggle({ label, value, disabled, onChange }: { label: string; value: boolean; disabled: boolean; onChange: (value: boolean) => void }) { return <View style={styles.toggle}><Text style={styles.toggleLabel}>{label}</Text><Switch value={value} disabled={disabled} onValueChange={onChange} trackColor={{ false: colors.border, true: colors.dangerDark }} thumbColor={value ? colors.danger : colors.muted} /></View>; }
function Stat({ value, label }: { value: number; label: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function safetyLabel(status?: string) { return status === 'safe' ? '安全' : status === 'attention' ? '需关注' : status === 'danger' ? '危险' : '状态未知'; }
const styles = StyleSheet.create({ loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, back: { color: colors.info, fontWeight: '800' }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.lg, gap: spacing.md }, title: { color: colors.text, fontSize: 18, fontWeight: '900' }, body: { color: colors.muted, lineHeight: 21 }, input: { height: 52, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.background, color: colors.text, paddingHorizontal: spacing.md }, primary: { height: 50, backgroundColor: colors.danger, borderRadius: radius.sm, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: colors.white, fontWeight: '900' }, secondary: { height: 50, borderColor: colors.info, borderWidth: 1, borderRadius: radius.sm, alignItems: 'center', justifyContent: 'center' }, secondaryText: { color: colors.info, fontWeight: '900' }, hero: { backgroundColor: '#172554', borderColor: '#3B82F666', borderWidth: 1, borderRadius: radius.lg, padding: spacing.lg, gap: spacing.sm }, familyName: { color: colors.text, fontSize: 25, fontWeight: '900' }, code: { color: '#93C5FD', fontWeight: '800', letterSpacing: 1 }, stats: { flexDirection: 'row', marginTop: spacing.sm }, stat: { flex: 1, alignItems: 'center' }, statValue: { color: colors.white, fontSize: 22, fontWeight: '900' }, statLabel: { color: '#93C5FD', fontSize: 11 }, member: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth }, online: { width: 9, height: 9, borderRadius: 5, backgroundColor: colors.safe }, offline: { backgroundColor: colors.muted }, memberBody: { flex: 1 }, memberName: { color: colors.text, fontWeight: '800' }, role: { color: colors.info, fontSize: 10 }, memberMeta: { color: colors.muted, fontSize: 11, marginTop: 3 }, locate: { color: colors.info, fontWeight: '800' }, more: { color: colors.muted, fontWeight: '900', letterSpacing: 2 }, toggle: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, toggleLabel: { color: '#E2E8F0', fontWeight: '700' }, leave: { height: 50, borderColor: '#EF444466', borderWidth: 1, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, leaveText: { color: colors.danger, fontWeight: '900' } });
