import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen';
import { supabase } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';
import type { RootStackParams } from '../navigation/RootNavigator';
type Props = NativeStackScreenProps<RootStackParams, 'NotificationSettings'>;
type Form = { push_enabled: boolean; email_enabled: boolean; sms_enabled: boolean; sound_enabled: boolean; vibration_enabled: boolean; flash_enabled: boolean; critical_alerts_enabled: boolean; dnd_enabled: boolean; dnd_start_time: string; dnd_end_time: string; dnd_repeat: string };
const defaults: Form = { push_enabled: true, email_enabled: false, sms_enabled: false, sound_enabled: true, vibration_enabled: true, flash_enabled: true, critical_alerts_enabled: true, dnd_enabled: false, dnd_start_time: '22:00', dnd_end_time: '07:00', dnd_repeat: 'daily' };
export function NotificationSettingsScreen({ navigation }: Props) {
  const [form, setForm] = useState(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { void (async () => { const { data: auth } = await supabase.auth.getUser(); if (auth.user) { const { data } = await supabase.from('user_alert_settings').select('*').eq('user_id', auth.user.id).maybeSingle(); if (data) setForm({ ...defaults, ...data, dnd_start_time: String(data.dnd_start_time || '22:00').slice(0, 5), dnd_end_time: String(data.dnd_end_time || '07:00').slice(0, 5) }); } setLoading(false); })(); }, []);
  const toggle = (key: keyof Form) => setForm((current) => ({ ...current, [key]: !current[key] }));
  const save = async () => { setSaving(true); const { data: auth } = await supabase.auth.getUser(); const { error } = auth.user ? await supabase.from('user_alert_settings').upsert({ user_id: auth.user.id, ...form }, { onConflict: 'user_id' }) : { error: new Error('登录已失效') }; setSaving(false); Alert.alert(error ? '保存失败' : '通知设置已同步', error?.message || '后台会按新的渠道和免打扰规则发送通知'); };
  if (loading) return <View style={styles.loading}><ActivityIndicator color={colors.info} size="large" /></View>;
  return <Screen title="通知设置" subtitle="推送、短信、邮件与免打扰" action={<Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>返回</Text></Pressable>}>
    <View style={styles.card}><Text style={styles.title}>通知渠道</Text><Toggle label="App推送" value={form.push_enabled} onChange={() => toggle('push_enabled')} /><Toggle label="短信通知（红色预警）" value={form.sms_enabled} onChange={() => toggle('sms_enabled')} /><Toggle label="邮件通知（红色预警）" value={form.email_enabled} onChange={() => toggle('email_enabled')} /></View>
    <View style={styles.card}><Text style={styles.title}>提醒效果</Text><Toggle label="声音" value={form.sound_enabled} onChange={() => toggle('sound_enabled')} /><Toggle label="震动" value={form.vibration_enabled} onChange={() => toggle('vibration_enabled')} /><Toggle label="红色闪烁" value={form.flash_enabled} onChange={() => toggle('flash_enabled')} /><Toggle label="强提醒" value={form.critical_alerts_enabled} onChange={() => toggle('critical_alerts_enabled')} /></View>
    <View style={styles.card}><Text style={styles.title}>免打扰</Text><Toggle label="启用免打扰时段" value={form.dnd_enabled} onChange={() => toggle('dnd_enabled')} /><View style={styles.timeRow}><Field label="开始" value={form.dnd_start_time} onChangeText={(v) => setForm((c) => ({ ...c, dnd_start_time: v.slice(0, 5) }))} /><Field label="结束" value={form.dnd_end_time} onChangeText={(v) => setForm((c) => ({ ...c, dnd_end_time: v.slice(0, 5) }))} /></View><Text style={styles.label}>重复</Text><View style={styles.options}>{([['daily', '每天'], ['weekdays', '工作日'], ['custom', '自定义']] as const).map(([value, label]) => <Pressable key={value} style={[styles.choice, form.dnd_repeat === value && styles.choiceActive]} onPress={() => setForm((c) => ({ ...c, dnd_repeat: value }))}><Text style={[styles.choiceText, form.dnd_repeat === value && styles.choiceTextActive]}>{label}</Text></Pressable>)}</View><Text style={styles.note}>红色生命安全预警不受普通免打扰限制；iOS强提醒仍需系统授权。</Text></View>
    <Pressable style={styles.save} onPress={save} disabled={saving}>{saving ? <ActivityIndicator color={colors.white} /> : <Text style={styles.saveText}>保存通知设置</Text>}</Pressable>
  </Screen>;
}
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: () => void }) { return <View style={styles.toggle}><Text style={styles.toggleLabel}>{label}</Text><Switch value={value} onValueChange={onChange} trackColor={{ false: colors.border, true: colors.dangerDark }} thumbColor={value ? colors.danger : colors.muted} /></View>; }
function Field({ label, ...props }: React.ComponentProps<typeof TextInput> & { label: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} placeholder="HH:MM" placeholderTextColor={colors.muted} keyboardType="numbers-and-punctuation" /></View>; }
const styles = StyleSheet.create({ loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, back: { color: colors.info, fontWeight: '800' }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.lg, gap: spacing.sm }, title: { color: colors.text, fontSize: 18, fontWeight: '900' }, toggle: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, toggleLabel: { color: '#E2E8F0', fontWeight: '700' }, timeRow: { flexDirection: 'row', gap: spacing.md }, field: { flex: 1, gap: 5 }, label: { color: colors.muted, fontSize: 12, fontWeight: '700' }, input: { height: 46, borderRadius: radius.sm, borderColor: colors.border, borderWidth: 1, backgroundColor: colors.background, color: colors.text, paddingHorizontal: spacing.md }, options: { flexDirection: 'row', gap: spacing.sm }, choice: { minHeight: 40, paddingHorizontal: spacing.md, borderRadius: radius.sm, backgroundColor: colors.surfaceRaised, justifyContent: 'center' }, choiceActive: { backgroundColor: colors.info }, choiceText: { color: colors.muted, fontWeight: '800' }, choiceTextActive: { color: colors.background }, note: { color: colors.warning, lineHeight: 19, fontSize: 12 }, save: { height: 52, borderRadius: radius.md, backgroundColor: colors.danger, alignItems: 'center', justifyContent: 'center' }, saveText: { color: colors.white, fontWeight: '900' } });
