import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen';
import { supabase } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';
import type { RootStackParams } from '../navigation/RootNavigator';

type Props = NativeStackScreenProps<RootStackParams, 'Notifications'>;
export function NotificationsScreen({ navigation }: Props) {
  const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [errorMessage, setErrorMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); const { data, error } = await supabase.from('notifications').select('*').order('created_at', { ascending: false }).limit(100); if (error) setErrorMessage('通知加载失败，请检查网络后重试。'); else { setRows(data || []); setErrorMessage(''); } setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);
  const read = async (row:any) => { if (!row.is_read) { const { error } = await supabase.from('notifications').update({ is_read: true, read_at: new Date().toISOString() }).eq('id', row.id); if (error) return Alert.alert('更新失败', '通知状态未能同步，请稍后重试。'); } setRows(old=>old.map(x=>x.id===row.id?{...x,is_read:true}:x)); const alertId=row.data?.alert_id; const sosId=row.data?.sos_id; if(alertId) navigation.navigate('AlertDetail',{alertId}); else if(sosId) navigation.navigate('SOSHistory'); };
  const readAll = async () => { const { data:{user} }=await supabase.auth.getUser(); if(!user) return Alert.alert('登录已失效', '请重新登录后再试。'); const { error } = await supabase.from('notifications').update({is_read:true,read_at:new Date().toISOString()}).eq('user_id',user.id).eq('is_read',false); if (error) return Alert.alert('更新失败', '未能将通知全部标为已读。'); await load(); };
  return <Screen title="通知中心" subtitle={`${rows.filter(x=>!x.is_read).length} 条未读`} action={<Pressable onPress={()=>navigation.goBack()}><Text style={styles.link}>返回</Text></Pressable>} refreshing={loading} onRefresh={()=>void load()}>{errorMessage ? <View style={styles.error}><Text style={styles.errorText}>{errorMessage}</Text><Pressable onPress={()=>void load()}><Text style={styles.retry}>重新加载</Text></Pressable></View> : null}<Pressable style={styles.all} onPress={()=>void readAll()} disabled={!rows.length}><Text style={styles.allText}>全部标为已读</Text></Pressable>{rows.map(row=><Pressable key={row.id} style={[styles.card,!row.is_read&&styles.unread]} onPress={()=>void read(row)}><View style={styles.heading}><Text style={styles.title}>{row.title}</Text>{!row.is_read&&<View style={styles.dot}/>}</View><Text style={styles.body}>{row.body}</Text><Text style={styles.time}>{new Date(row.created_at).toLocaleString('zh-CN')}</Text></Pressable>)}{!rows.length&&!errorMessage&&<Text style={styles.empty}>暂无通知</Text>}</Screen>;
}
const styles=StyleSheet.create({link:{color:colors.info,fontWeight:'800'},error:{backgroundColor:'#7F1D1D44',borderColor:colors.danger,borderWidth:1,borderRadius:radius.md,padding:spacing.md,gap:spacing.sm},errorText:{color:'#FECACA'},retry:{color:colors.info,fontWeight:'900'},all:{alignSelf:'flex-end',padding:spacing.sm},allText:{color:colors.info,fontWeight:'800'},card:{backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:radius.md,padding:spacing.md,gap:spacing.sm},unread:{borderColor:colors.info,backgroundColor:'#0EA5E911'},heading:{flexDirection:'row',alignItems:'center'},title:{color:colors.text,fontWeight:'900',fontSize:16,flex:1},dot:{width:8,height:8,borderRadius:4,backgroundColor:colors.danger},body:{color:'#CBD5E1',lineHeight:20},time:{color:colors.muted,fontSize:11},empty:{color:colors.muted,textAlign:'center',padding:60}});
