import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as FileSystem from 'expo-file-system/legacy';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen';
import { supabase } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';
import type { RootStackParams } from '../navigation/RootNavigator';
import type { OfflinePack } from '../lib/offlinePacks';
type Props = NativeStackScreenProps<RootStackParams, 'OfflineMaps'>;
export function OfflineMapsScreen({ navigation }: Props) {
  const [packs, setPacks] = useState<OfflinePack[]>([]); const [city, setCity] = useState(''); const [country, setCountry] = useState(''); const [busy, setBusy] = useState(false); const [faq, setFaq] = useState<number | null>(null);
  useEffect(() => { void (async () => { const [saved, auth] = await Promise.all([AsyncStorage.getItem('offline-map-packs'), supabase.auth.getUser()]); if (saved) setPacks(JSON.parse(saved)); if (auth.data.user) { const { data } = await supabase.from('profiles').select('city,country').eq('id', auth.data.user.id).maybeSingle(); setCity(data?.city || 'Kyiv'); setCountry(data?.country || 'Ukraine'); } })(); }, []);
  const persist = async (next: OfflinePack[]) => { setPacks(next); await AsyncStorage.setItem('offline-map-packs', JSON.stringify(next)); };
  const download = async () => { if (!city) return navigation.navigate('CitySelect'); setBusy(true); try { const [alerts, shelters] = await Promise.all([supabase.from('alerts').select('*').eq('city', city).order('created_at', { ascending: false }).limit(300), supabase.from('shelters').select('*').eq('city', city).limit(500)]); if (alerts.error || shelters.error) throw alerts.error || shelters.error; const payload = JSON.stringify({ version: 1, city, country, downloadedAt: new Date().toISOString(), alerts: alerts.data || [], shelters: shelters.data || [] }); const directory = `${FileSystem.documentDirectory}offline-maps/`; await FileSystem.makeDirectoryAsync(directory, { intermediates: true }); const path = `${directory}${encodeURIComponent(country)}-${encodeURIComponent(city)}.json`; await FileSystem.writeAsStringAsync(path, payload); const pack: OfflinePack = { city, country, path, size: payload.length * 2, downloadedAt: new Date().toISOString(), alerts: alerts.data?.length || 0, shelters: shelters.data?.length || 0 }; await persist([pack, ...packs.filter((item) => item.city !== city || item.country !== country)]); Alert.alert('????', `${city}?????????????????`); } catch (error) { Alert.alert('????', error instanceof Error ? error.message : '?????'); } finally { setBusy(false); } };
  const remove = (pack: OfflinePack) => Alert.alert('?????', `?? ${pack.city} ??????`, [{ text: '??', style: 'cancel' }, { text: '??', style: 'destructive', onPress: async () => { await FileSystem.deleteAsync(pack.path, { idempotent: true }); await persist(packs.filter((item) => item.path !== pack.path)); } }]);
  return <Screen title="????" subtitle="?????????" action={<Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>??</Text></Pressable>}>
    <View style={styles.info}><Text style={styles.infoTitle}>?????????</Text><Text style={styles.infoText}>?????????????????????????????????????????????Google??????????Google Maps????</Text></View>
    <View style={styles.card}><Text style={styles.title}>????</Text><Text style={styles.city}>{city || '???'} ? {country || '???'}</Text><Pressable onPress={() => navigation.navigate('CitySelect')}><Text style={styles.link}>????</Text></Pressable><Pressable style={styles.download} onPress={() => void download()} disabled={busy}>{busy ? <ActivityIndicator color={colors.background} /> : <Text style={styles.downloadText}>??/???????</Text>}</Pressable></View>
    <View style={styles.card}><Text style={styles.title}>?????</Text>{packs.length ? packs.map((pack) => <View key={pack.path} style={styles.pack}><View style={styles.packBody}><Text style={styles.packTitle}>{pack.city} ? {pack.country}</Text><Text style={styles.packMeta}>{formatBytes(pack.size)} ? {pack.shelters}???? ? {pack.alerts}???</Text><Text style={styles.packMeta}>??? {new Date(pack.downloadedAt).toLocaleString('zh-CN')}</Text></View><Pressable onPress={() => remove(pack)}><Text style={styles.delete}>??</Text></Pressable></View>) : <Text style={styles.empty}>????????</Text>}</View>
    <View style={styles.card}><Text style={styles.title}>????</Text>{[['????????', '?????????????????App???????????????'], ['????Google???', '??????????Google?????Google????????Google Maps App??????????'], ['???????', '???????????????????????????????']].map(([q, a], index) => <Pressable key={q} style={styles.faq} onPress={() => setFaq(faq === index ? null : index)}><Text style={styles.question}>{q}</Text>{faq === index ? <Text style={styles.answer}>{a}</Text> : null}</Pressable>)}</View>
  </Screen>;
}
function formatBytes(value: number) { return value < 1024 ? `${value} B` : value < 1048576 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1048576).toFixed(1)} MB`; }
const styles = StyleSheet.create({ back: { color: colors.info, fontWeight: '800' }, info: { backgroundColor: '#172554', borderColor: '#3B82F666', borderWidth: 1, borderRadius: radius.md, padding: spacing.lg, gap: spacing.sm }, infoTitle: { color: '#BFDBFE', fontWeight: '900', fontSize: 18 }, infoText: { color: '#DBEAFE', lineHeight: 22 }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.lg, gap: spacing.md }, title: { color: colors.text, fontSize: 18, fontWeight: '900' }, city: { color: colors.info, fontSize: 20, fontWeight: '900' }, link: { color: colors.info, fontWeight: '800' }, download: { height: 50, borderRadius: radius.sm, backgroundColor: colors.info, alignItems: 'center', justifyContent: 'center' }, downloadText: { color: colors.background, fontWeight: '900' }, pack: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.sm, borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth }, packBody: { flex: 1 }, packTitle: { color: colors.text, fontWeight: '900' }, packMeta: { color: colors.muted, fontSize: 11, marginTop: 4 }, delete: { color: colors.danger, fontWeight: '800' }, empty: { color: colors.muted }, faq: { paddingVertical: spacing.sm, borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth }, question: { color: colors.text, fontWeight: '800' }, answer: { color: colors.muted, lineHeight: 20, marginTop: spacing.sm } });
