import { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useFocusEffect } from '@react-navigation/native';
import { Screen } from '../components/Screen';
import { supabase } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';
import type { RootStackParams } from '../navigation/RootNavigator';
type Props = NativeStackScreenProps<RootStackParams, 'ProfileEdit'>;
type Form = { nickname: string; avatar_url: string; phone: string; email: string; gender: string; birth_date: string; city: string; country: string };
const empty: Form = { nickname: '', avatar_url: '', phone: '', email: '', gender: 'secret', birth_date: '', city: '', country: '' };
export function ProfileEditScreen({ navigation }: Props) {
  const [form, setForm] = useState(empty); const [userId, setUserId] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return; setUserId(auth.user.id); const { data } = await supabase.from('profiles').select('nickname,avatar_url,phone,email,gender,birth_date,city,country').eq('id', auth.user.id).maybeSingle(); setForm({ ...empty, phone: auth.user.phone || '', email: auth.user.email || '', ...(data || {}) } as Form); setLoading(false); }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const update = (key: keyof Form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const pickAvatar = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [1, 1], quality: 0.8 }); if (result.canceled || !result.assets[0] || !userId) return; setSaving(true); try { const asset = result.assets[0]; const response = await fetch(asset.uri); const bytes = await response.arrayBuffer(); const extension = asset.mimeType?.split('/')[1] || 'jpg'; const path = `${userId}/avatar.${extension}`; const uploaded = await supabase.storage.from('avatars').upload(path, bytes, { contentType: asset.mimeType || 'image/jpeg', upsert: true }); if (uploaded.error) throw uploaded.error; const { data } = supabase.storage.from('avatars').getPublicUrl(path); update('avatar_url', `${data.publicUrl}?v=${Date.now()}`); } catch (error) { Alert.alert('??????', error instanceof Error ? error.message : '?????'); } finally { setSaving(false); } };
  const save = async () => { if (!form.nickname.trim()) return Alert.alert('?????'); setSaving(true); const { error } = await supabase.from('profiles').update({ nickname: form.nickname.trim(), avatar_url: form.avatar_url || null, gender: form.gender, birth_date: form.birth_date || null, city: form.city.trim() || null, country: form.country.trim() || null }).eq('id', userId); setSaving(false); if (error) Alert.alert('????', error.message); else Alert.alert('?????'); };
  if (loading) return <View style={styles.loading}><ActivityIndicator color={colors.info} size="large" /></View>;
  return <Screen title="????" subtitle="??????" action={<Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>??</Text></Pressable>}>
    <View style={styles.avatarBox}>{form.avatar_url ? <Image source={{ uri: form.avatar_url }} style={styles.avatar} /> : <View style={[styles.avatar, styles.avatarFallback]}><Text style={styles.avatarText}>{(form.nickname || 'W').slice(0, 1).toUpperCase()}</Text></View>}<Pressable onPress={() => void pickAvatar()}><Text style={styles.avatarLink}>????</Text></Pressable></View>
    <View style={styles.card}><Field label="??" value={form.nickname} onChangeText={(v) => update('nickname', v)} /><Field label="???????" value={form.phone || '???'} editable={false} /><Field label="??????" value={form.email || '???'} editable={false} /><Text style={styles.label}>??</Text><View style={styles.choices}>{([['male', '?'], ['female', '?'], ['secret', '??']] as const).map(([value, label]) => <Choice key={value} label={label} active={form.gender === value} onPress={() => update('gender', value)} />)}</View><Field label="???YYYY-MM-DD?" value={form.birth_date || ''} onChangeText={(v) => update('birth_date', v)} /><Pressable style={styles.city} onPress={() => navigation.navigate('CitySelect')}><View><Text style={styles.label}>????</Text><Text style={styles.cityValue}>{[form.city, form.country].filter(Boolean).join(' ? ') || '?????'}</Text></View><Text style={styles.chevron}>?</Text></Pressable></View>
    <Pressable style={styles.save} onPress={save} disabled={saving}>{saving ? <ActivityIndicator color={colors.white} /> : <Text style={styles.saveText}>??????</Text>}</Pressable>
  </Screen>;
}
function Field({ label, ...props }: React.ComponentProps<typeof TextInput> & { label: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} style={[styles.input, props.editable === false && styles.disabled]} placeholder={label} placeholderTextColor={colors.muted} /></View>; }
function Choice({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable style={[styles.choice, active && styles.choiceActive]} onPress={onPress}><Text style={[styles.choiceText, active && styles.choiceTextActive]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, back: { color: colors.info, fontWeight: '800' }, avatarBox: { alignItems: 'center', gap: spacing.sm }, avatar: { width: 94, height: 94, borderRadius: 32 }, avatarFallback: { backgroundColor: '#0C4A6E', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.info, fontSize: 35, fontWeight: '900' }, avatarLink: { color: colors.info, fontWeight: '800' }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.lg, gap: spacing.md }, field: { gap: 6 }, label: { color: colors.muted, fontSize: 12, fontWeight: '700' }, input: { height: 50, borderRadius: radius.sm, borderColor: colors.border, borderWidth: 1, backgroundColor: colors.background, color: colors.text, paddingHorizontal: spacing.md }, disabled: { opacity: 0.65 }, choices: { flexDirection: 'row', gap: spacing.sm }, choice: { height: 40, paddingHorizontal: spacing.lg, borderRadius: radius.sm, backgroundColor: colors.surfaceRaised, alignItems: 'center', justifyContent: 'center' }, choiceActive: { backgroundColor: colors.info }, choiceText: { color: colors.muted, fontWeight: '800' }, choiceTextActive: { color: colors.background }, city: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, cityValue: { color: colors.text, marginTop: 5, fontWeight: '800' }, chevron: { color: colors.muted, fontSize: 27 }, save: { height: 52, borderRadius: radius.md, backgroundColor: colors.danger, alignItems: 'center', justifyContent: 'center' }, saveText: { color: colors.white, fontWeight: '900' } });
