import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Linking, Pressable, Share, StyleSheet, Text, View } from 'react-native';
import * as Location from 'expo-location';
import AsyncStorage from '@react-native-async-storage/async-storage';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { NativeGoogleMap } from '../components/NativeGoogleMap';
import { Screen } from '../components/Screen';
import { supabase } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';
import type { RootStackParams } from '../navigation/RootNavigator';
type Props = NativeStackScreenProps<RootStackParams, 'RoutePlan'>;
type Route = { id: string; summary: string; coordinates: Array<{ latitude: number; longitude: number }>; distanceText: string; durationText: string; safetyScore: number; dangerWarnings: Array<{ id: string; title: string; severity: string }> };
export function RoutePlanScreen({ route, navigation }: Props) {
  const destination = route.params; const [origin, setOrigin] = useState<{ latitude: number; longitude: number } | null>(null); const [routes, setRoutes] = useState<Route[]>([]); const [selectedId, setSelectedId] = useState(''); const [mode, setMode] = useState<'walking' | 'driving'>('walking'); const [loading, setLoading] = useState(true);
  const plan = async (currentOrigin: { latitude: number; longitude: number }, travelMode = mode) => { setLoading(true); const cached = JSON.parse(await AsyncStorage.getItem('map-preferences') || '{}'); const language = await AsyncStorage.getItem('app-language') || 'zh'; const avoid = [cached.avoid_highways && 'highways', cached.avoid_tolls && 'tolls', cached.avoid_ferries && 'ferries'].filter(Boolean); const { data, error } = await supabase.functions.invoke('route-service', { body: { origin: currentOrigin, destination, mode: travelMode, avoid, language } }); setLoading(false); if (error || !data?.success) return Alert.alert('??????', data?.error || error?.message || '?????'); setRoutes(data.routes || []); const preferred = cached.route_preference === 'fastest' ? data.fastestId : cached.route_preference === 'shortest' ? data.shortestId : data.safestId; setSelectedId(preferred || data.safestId || data.fastestId || data.routes?.[0]?.id || ''); };
  useEffect(() => { void (async () => { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') { setLoading(false); return Alert.alert('????', '??????????'); } const location = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.High }); const point = { latitude: location.coords.latitude, longitude: location.coords.longitude }; setOrigin(point); await plan(point); })(); }, []);
  const selected = useMemo(() => routes.find((item) => item.id === selectedId) || routes[0], [routes, selectedId]);
  const changeMode = async (value: 'walking' | 'driving') => { setMode(value); if (origin) await plan(origin, value); };
  const openNavigation = () => void Linking.openURL(`https://www.google.com/maps/dir/?api=1&destination=${destination.latitude},${destination.longitude}&travelmode=${mode}`);
  return <Screen title="????" subtitle={destination.name} action={<Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>??</Text></Pressable>}>
    <View style={styles.mode}><Choice label="??" active={mode === 'walking'} onPress={() => void changeMode('walking')} /><Choice label="??" active={mode === 'driving'} onPress={() => void changeMode('driving')} /><Pressable style={styles.refresh} onPress={() => origin && void plan(origin)}><Text style={styles.refreshText}>????</Text></Pressable></View>
    {origin ? <NativeGoogleMap center={origin} showsUserLocation markers={[{ id: 'destination', latitude: destination.latitude, longitude: destination.longitude, title: destination.name, color: colors.safe }]} route={selected?.coordinates || []} zoom={0.08} /> : null}
    {loading ? <ActivityIndicator color={colors.info} size="large" /> : routes.map((item, index) => <Pressable key={item.id} style={[styles.routeCard, selectedId === item.id && styles.routeActive]} onPress={() => setSelectedId(item.id)}><View style={styles.routeTop}><Text style={styles.routeTitle}>{index === 0 ? '????' : `?? ${index + 1}`} ? {item.summary}</Text><Text style={[styles.score, { color: item.safetyScore >= 80 ? colors.safe : item.safetyScore >= 50 ? colors.warning : colors.danger }]}>?? {item.safetyScore}</Text></View><Text style={styles.routeMeta}>{item.distanceText} ? ?? {item.durationText}</Text>{item.dangerWarnings.length ? <Text style={styles.warning}>?? {item.dangerWarnings.length} ?????????????????</Text> : <Text style={styles.safe}>???????????</Text>}</Pressable>)}
    <Pressable style={styles.primary} onPress={openNavigation} disabled={!selected}><Text style={styles.primaryText}>?? Google Maps ??</Text></Pressable><Pressable style={styles.secondary} onPress={() => void Share.share({ message: `WarRescue?????${destination.name}\nhttps://www.google.com/maps/dir/?api=1&destination=${destination.latitude},${destination.longitude}&travelmode=${mode}` })}><Text style={styles.secondaryText}>????</Text></Pressable>
  </Screen>;
}
function Choice({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable style={[styles.choice, active && styles.choiceActive]} onPress={onPress}><Text style={[styles.choiceText, active && styles.choiceTextActive]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ back: { color: colors.info, fontWeight: '800' }, mode: { flexDirection: 'row', gap: spacing.sm }, choice: { paddingHorizontal: spacing.md, height: 42, borderRadius: radius.sm, backgroundColor: colors.surfaceRaised, alignItems: 'center', justifyContent: 'center' }, choiceActive: { backgroundColor: colors.info }, choiceText: { color: colors.muted, fontWeight: '800' }, choiceTextActive: { color: colors.background }, refresh: { marginLeft: 'auto', justifyContent: 'center' }, refreshText: { color: colors.info, fontWeight: '800' }, routeCard: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.md, gap: spacing.sm }, routeActive: { borderColor: colors.info, backgroundColor: '#0C4A6E44' }, routeTop: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, routeTitle: { color: colors.text, flex: 1, fontWeight: '900' }, score: { fontWeight: '900' }, routeMeta: { color: colors.info, fontWeight: '700' }, warning: { color: colors.warning, fontSize: 12 }, safe: { color: colors.safe, fontSize: 12 }, primary: { height: 52, borderRadius: radius.md, backgroundColor: colors.safe, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: colors.background, fontWeight: '900' }, secondary: { height: 50, borderRadius: radius.md, borderColor: colors.info, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, secondaryText: { color: colors.info, fontWeight: '900' } });
