import { useEffect, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen';
import { supabase } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';
import type { ShelterRow } from '../types';
import type { RootStackParams } from '../navigation/RootNavigator';
import { NativeGoogleMap } from '../components/NativeGoogleMap';
type Props = NativeStackScreenProps<RootStackParams, 'ShelterDetail'>;
export function ShelterDetailScreen({ route, navigation }: Props) {
  const [shelter, setShelter] = useState<ShelterRow | null>(null);
  useEffect(() => { void supabase.from('shelters').select('*').eq('id', route.params.shelterId).maybeSingle().then(({ data }) => setShelter(data as ShelterRow | null)); }, [route.params.shelterId]);
  if (!shelter) return <View style={styles.loading}><ActivityIndicator color={colors.safe} size="large" /></View>;
  const status = ({ open: '开放', crowded: '拥挤', full: '已满', closed: '关闭' } as Record<string, string>)[shelter.status || ''] || '状态未知';
  const navigate = (mode: 'walking' | 'driving') => void Linking.openURL(`https://www.google.com/maps/dir/?api=1&destination=${shelter.latitude},${shelter.longitude}&travelmode=${mode}`);
  return <Screen title="避难所详情" subtitle={status} action={<Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>返回</Text></Pressable>}>
    <NativeGoogleMap center={{ latitude: shelter.latitude, longitude: shelter.longitude }} markers={[{ id: shelter.id, latitude: shelter.latitude, longitude: shelter.longitude, title: shelter.name, description: shelter.address || undefined, color: colors.safe }]} radiusMeters={250} radiusColor={colors.safe} zoom={0.025} />
    <View style={styles.card}><View style={styles.heading}><View style={styles.headingBody}><Text style={styles.name}>{shelter.name}</Text><Text style={styles.address}>{shelter.address || [shelter.city, shelter.country].filter(Boolean).join(', ')}</Text></View><Text style={[styles.status, shelter.status === 'open' ? styles.open : shelter.status === 'closed' ? styles.closed : styles.crowded]}>{status}</Text></View>{route.params.distance != null ? <Row label="当前位置距离" value={`${route.params.distance.toFixed(1)} km`} /> : null}<Row label="容量" value={shelter.capacity ? `${shelter.current_occupancy || 0} / ${shelter.capacity}` : '未公布'} /><Row label="开放时间" value={shelter.opening_hours || '全天或以现场公告为准'} /><Row label="联系电话" value={shelter.phone || '未提供'} />{shelter.phone ? <Pressable onPress={() => void Linking.openURL(`tel:${shelter.phone}`)}><Text style={styles.link}>拨打避难所电话</Text></Pressable> : null}</View>
    <View style={styles.card}><Text style={styles.section}>设施</Text><View style={styles.facilities}><Facility label="饮用水" active={!!shelter.has_water} /><Facility label="电力" active={!!shelter.has_electricity} /><Facility label="医疗" active={!!shelter.has_medical} /><Facility label="卫生间" active={!!shelter.has_toilet} /><Facility label="休息区" active={!!shelter.has_rest_area} /></View></View>
    <Pressable style={styles.primary} onPress={() => navigate('walking')}><Text style={styles.primaryText}>Google Maps 步行导航</Text></Pressable><Pressable style={styles.secondary} onPress={() => navigation.navigate('RoutePlan', { latitude: shelter.latitude, longitude: shelter.longitude, name: shelter.name })}><Text style={styles.secondaryText}>App内规划多条逃生路线</Text></Pressable>
    {shelter.updated_at ? <Text style={styles.updated}>信息更新时间：{new Date(shelter.updated_at).toLocaleString('zh-CN')}</Text> : null}
  </Screen>;
}
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
function Facility({ label, active }: { label: string; active: boolean }) { return <View style={[styles.facility, active && styles.facilityActive]}><Text style={[styles.facilityText, active && styles.facilityTextActive]}>{active ? '✓ ' : '— '}{label}</Text></View>; }
const styles = StyleSheet.create({ loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, back: { color: colors.info, fontWeight: '800' }, map: { height: 230, borderRadius: radius.lg, backgroundColor: '#0D2230', borderColor: colors.border, borderWidth: 1, alignItems: 'center', justifyContent: 'center', gap: spacing.sm }, safeRange: { width: 140, height: 140, borderRadius: 70, borderColor: colors.safe, borderWidth: 2, backgroundColor: '#22C55E14', alignItems: 'center', justifyContent: 'center' }, pin: { color: colors.safe, fontSize: 48, fontWeight: '900' }, coords: { color: colors.muted, fontSize: 12 }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.lg, gap: spacing.md }, heading: { flexDirection: 'row', gap: spacing.md }, headingBody: { flex: 1 }, name: { color: colors.text, fontSize: 22, fontWeight: '900' }, address: { color: colors.muted, lineHeight: 20, marginTop: 5 }, status: { fontWeight: '900' }, open: { color: colors.safe }, crowded: { color: colors.warning }, closed: { color: colors.danger }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.md }, label: { color: colors.muted }, value: { color: colors.text, fontWeight: '700', flex: 1, textAlign: 'right' }, link: { color: colors.info, fontWeight: '800' }, section: { color: colors.text, fontSize: 17, fontWeight: '900' }, facilities: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, facility: { paddingHorizontal: 12, paddingVertical: 9, borderRadius: radius.round, backgroundColor: colors.surfaceRaised }, facilityActive: { backgroundColor: '#22C55E22' }, facilityText: { color: colors.muted, fontWeight: '700' }, facilityTextActive: { color: colors.safe }, primary: { height: 52, borderRadius: radius.md, backgroundColor: colors.safe, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: colors.background, fontWeight: '900' }, secondary: { height: 52, borderRadius: radius.md, borderColor: colors.safe, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, secondaryText: { color: colors.safe, fontWeight: '900' }, updated: { color: colors.muted, textAlign: 'center', fontSize: 11 } });
