import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Linking, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { finishTransaction, useIAP, type DiscountOfferInputIOS, type ProductSubscription, type Purchase } from 'expo-iap';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen';
import { supabase } from '../lib/supabase';
import { colors, radius, spacing } from '../theme';
import type { RootStackParams } from '../navigation/RootNavigator';

type Props = NativeStackScreenProps<RootStackParams, 'Subscription'>;
type Status = { hasSubscription?: boolean; planId?: string; status?: string; expiresAt?: string; daysUntilExpiry?: number; autoRenew?: boolean; isTrialActive?: boolean; trialEndsAt?: string };
const PRODUCTS = [
  { id: 'com.warrescue.app.personal.monthly', plan: 'personal', title: '????', fallback: '$39.99/?', features: ['????????', 'SOS?????', '1????'] },
  { id: 'com.warrescue.app.family.monthly', plan: 'family', title: '????', fallback: '$99.99/?', features: ['?????????', '??6?????', '?????????SOS??'] },
] as const;

export function SubscriptionScreen({ navigation }: Props) {
  const [status, setStatus] = useState<Status>({}); const [coupons, setCoupons] = useState(0); const [busy, setBusy] = useState(false); const processing = useRef(new Set<string>());
  const loadStatus = useCallback(async () => { const [result, referral] = await Promise.all([supabase.functions.invoke('apple-iap', { body: { action: 'get-subscription-status' } }), supabase.functions.invoke('apple-iap', { body: { action: 'get-referral' } })]); if (result.data) setStatus(result.data); if (referral.data) setCoupons(referral.data.availableCoupons || 0); }, []);
  const verify = useCallback(async (purchase: Purchase) => { const key = purchase.purchaseToken || purchase.transactionId || purchase.id; if (!key || processing.current.has(key)) return; processing.current.add(key); setBusy(true); try { if (!purchase.purchaseToken) throw new Error('Apple ???????????'); const { data, error } = await supabase.functions.invoke('apple-iap', { body: { action: 'verify-receipt', jwsTransaction: purchase.purchaseToken, transactionId: purchase.transactionId || purchase.id, productId: purchase.productId } }); if (error || !data?.success) throw new Error(data?.error || error?.message || '??????'); await finishTransaction({ purchase, isConsumable: false }); await supabase.functions.invoke('apple-iap', { body: { action: 'consume-coupon', transactionId: purchase.transactionId || purchase.id } }); await loadStatus(); Alert.alert('?????', `???? ${new Date(data.expiresAt).toLocaleString('zh-CN')}`); } catch (error) { Alert.alert('??????', error instanceof Error ? error.message : '???????'); } finally { processing.current.delete(key); setBusy(false); } }, [loadStatus]);
  const iap = useIAP({ onPurchaseSuccess: (purchase) => { void verify(purchase); }, onPurchaseError: (error) => { if (error.code !== 'user-cancelled') Alert.alert('????', error.message); setBusy(false); }, onError: (error) => Alert.alert('App Store ????', error.message) });
  useEffect(() => { void loadStatus(); }, [loadStatus]);
  useEffect(() => { if (iap.connected) void iap.fetchProducts({ skus: PRODUCTS.map((item) => item.id), type: 'subs' }); }, [iap.connected]);
  const storeProduct = (id: string) => iap.subscriptions.find((item) => item.id === id);
  const purchase = async (id: string) => { if (Platform.OS !== 'ios') return Alert.alert('?????', '?????????? Apple App Store ???'); if (!iap.connected) return Alert.alert('App Store ???', '?????? Apple ID ????'); setBusy(true); try { const { data: auth } = await supabase.auth.getUser(); let offer: DiscountOfferInputIOS | undefined; if (coupons > 0) { const signed = await supabase.functions.invoke('apple-iap', { body: { action: 'sign-promo-offer', productId: id } }); if (signed.data?.eligible) offer = { identifier: signed.data.offerId, keyIdentifier: signed.data.keyId, nonce: signed.data.nonce, timestamp: signed.data.timestamp, signature: signed.data.signature }; } await iap.requestPurchase({ request: { apple: { sku: id, appAccountToken: auth.user?.id, withOffer: offer }, google: { skus: [id] } }, type: 'subs' }); } catch (error) { setBusy(false); Alert.alert('??????', error instanceof Error ? error.message : '?????'); } };
  const restore = async () => { setBusy(true); try { await iap.restorePurchases(); await iap.getAvailablePurchases(); await loadStatus(); Alert.alert('??????', '?????? Apple ID ????????'); } catch (error) { Alert.alert('????', error instanceof Error ? error.message : '?????'); } finally { setBusy(false); } };
  return <Screen title="????" subtitle="? Apple App Store ????" action={<Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>??</Text></Pressable>}>
    {status.hasSubscription || status.isTrialActive ? <View style={styles.active}><Text style={styles.activeTitle}>{status.isTrialActive ? '?????' : `${status.planId === 'family' ? '???' : '???'}???`}</Text><Text style={styles.activeText}>???{status.status} ? {status.expiresAt || status.trialEndsAt ? `???? ${new Date(status.expiresAt || status.trialEndsAt!).toLocaleString('zh-CN')}` : '???? Apple ??'}</Text></View> : null}
    {coupons > 0 ? <View style={styles.coupon}><Text style={styles.couponTitle}>?? {coupons} ???5??</Text><Text style={styles.couponText}>???????????????????????</Text></View> : null}
    {PRODUCTS.map((plan) => <Plan key={plan.id} product={storeProduct(plan.id)} title={plan.title} price={storeProduct(plan.id)?.displayPrice || plan.fallback} features={plan.features} active={status.planId === plan.plan && status.status !== 'expired'} disabled={busy} onPress={() => void purchase(plan.id)} />)}
    {busy ? <ActivityIndicator color={colors.info} /> : null}
    <Pressable style={styles.restore} onPress={() => void restore()} disabled={busy}><Text style={styles.restoreText}>????</Text></Pressable>
    <Pressable onPress={() => void Linking.openURL('https://apps.apple.com/account/subscriptions')}><Text style={styles.manage}>? Apple ????????</Text></Pressable>
    <Text style={styles.legal}>????? Apple ID ????????????????24??????????? App Store ?????</Text>
  </Screen>;
}

function Plan({ product: _product, title, price, features, active, disabled, onPress }: { product?: ProductSubscription; title: string; price: string; features: readonly string[]; active: boolean; disabled: boolean; onPress: () => void }) { return <View style={[styles.plan, active && styles.planActive]}><View style={styles.planTop}><Text style={styles.planTitle}>{title}</Text><Text style={styles.price}>{price}</Text></View>{features.map((item) => <Text key={item} style={styles.feature}>? {item}</Text>)}<Pressable style={[styles.buy, (active || disabled) && styles.buyDisabled]} onPress={onPress} disabled={active || disabled}><Text style={styles.buyText}>{active ? '????' : '?? Apple ??'}</Text></Pressable></View>; }
const styles = StyleSheet.create({ back: { color: colors.info, fontWeight: '800' }, active: { backgroundColor: '#052E16', borderColor: '#22C55E66', borderWidth: 1, borderRadius: radius.md, padding: spacing.lg, gap: spacing.sm }, activeTitle: { color: colors.safe, fontSize: 19, fontWeight: '900' }, activeText: { color: '#BBF7D0', lineHeight: 20 }, coupon: { backgroundColor: '#422006', borderColor: '#F59E0B66', borderWidth: 1, borderRadius: radius.md, padding: spacing.lg }, couponTitle: { color: colors.warning, fontWeight: '900' }, couponText: { color: '#FDE68A', marginTop: 6 }, plan: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.lg, padding: spacing.lg, gap: spacing.md }, planActive: { borderColor: colors.safe }, planTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, planTitle: { color: colors.text, fontSize: 21, fontWeight: '900' }, price: { color: colors.info, fontSize: 19, fontWeight: '900' }, feature: { color: '#CBD5E1' }, buy: { height: 49, borderRadius: radius.md, backgroundColor: colors.danger, alignItems: 'center', justifyContent: 'center' }, buyDisabled: { opacity: 0.45 }, buyText: { color: colors.white, fontWeight: '900' }, restore: { height: 48, borderColor: colors.info, borderWidth: 1, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, restoreText: { color: colors.info, fontWeight: '900' }, manage: { color: colors.info, textAlign: 'center', fontWeight: '800' }, legal: { color: colors.muted, fontSize: 11, lineHeight: 17, textAlign: 'center' } });
